# permissions for end users to view lendingschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lendingschedule-viewer-role
rules:
- apiGroups:
  - clusterlendingmanager.dtaniwaki.github.com
  resources:
  - lendingschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterlendingmanager.dtaniwaki.github.com
  resources:
  - lendingschedules/status
  verbs:
  - get
