# permissions for end users to edit lendingconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: LendingConfig-editor-role
rules:
- apiGroups:
  - clusterlendingmanager.dtaniwaki.github.com
  resources:
  - lendingconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterlendingmanager.dtaniwaki.github.com
  resources:
  - lendingconfigs/status
  verbs:
  - get
