---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - clusterlendingmanager.dtaniwaki.github.com
  resources:
  - lendingschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterlendingmanager.dtaniwaki.github.com
  resources:
  - lendingschedules/finalizers
  verbs:
  - update
- apiGroups:
  - clusterlendingmanager.dtaniwaki.github.com
  resources:
  - lendingschedules/status
  verbs:
  - get
  - patch
  - update
