apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-lending-manager-nginx
  annotations:
    clusterlendingmanager.dtaniwaki.github.com/default-replicas: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
